name = "build-n-bake"
author = "LeaderbotX400"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a638f94c6abc7d1e76f75d592f6700faa0c49c5c3663ac084600735ce5a38c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.197"
