name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Triggers workflow on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Repo Name
        run: echo "REPO_NAME=$(basename ${{github.repository}})" >> $REPO_NAME

        # Run the included ./pack-instance.sh script to generate .zip file for publishing
      - name: Run pack-instance script
        run: |
            chmod +x ./pack-instance.sh
            ./pack-instance.sh modpack_${{ env.REPO_NAME }}.zip
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: instance-package
          path: ./modpack_${{ env.REPO_NAME }}.zip
