name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Repo Name
        run: export REPO_NAME=$(basename ${{github.repository}})

        # Run the included ./pack-instance.sh script to generate .zip file for publishing
      - name: Run pack-instance script
        run: |
            chmod +x ./pack-instance.sh
            ./pack-instance.sh modpack.zip

      # Install Nix
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Export modpack to Modrinth
        run: nix run nixpkgs#packwiz modrinth export
    
      - name: Find Modrinth file
        run: | 
            echo "FILE_PATH=$(realpath $(find . -name "*.mrpack" | head -n 1))" >> $GITHUB_ENV

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: ${{ env.FILE_PATH }}
